[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "lox"
version = "0.1"
description = "Custom Interpreter"
authors = [{ name = "Mrinmoy" }]
dependencies = []